before:
  hooks:
    - go mod tidy
    - go mod verify
    - go mod download

builds:
  - goos:
      - linux
      - windows
      - darwin
      - freebsd

    goarch:
      - amd64
      - arm
      - arm64

    binary: lss

    main: ./cmd/lss.go

    ldflags: -s -w -X satstack/version.GitCommit={{.ShortCommit}} -X satstack/version.Build=release

    env:
      - GIN_MODE=release

checksum:
  name_template: '{{ tolower .ProjectName }}_{{.Version}}_checksums.txt'

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

archives:
  - name_template: "{{ tolower .ProjectName }}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      freebsd: FreeBSD

    files:
      - LICENSE

    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: ledgerhq
    name: satstack
